fix db
palevominimale/KPapi pull request #2
Opened 2022-12-14 20:12 UTC by LeskovBoris

Check cchanges, please. Especially, repos in data layer

2022-12-14 20:18 UTC, palevominimale requested changes

2022-12-14 20:18 UTC, palevominimale commented on domain/src/main/java/com/junopark/kpapi/domain/usecases/RoomUseCase.kt
> +    suspend fun getFilm(id:Int) = favsFilms.getFilm(id)
при каких обстоятельствах нам может потребоваться брать favorite by id?)

2022-12-14 20:18 UTC, palevominimale commented on data/src/main/java/com/junopark/kpapi/data/database/FavsFilmsDAO.kt
> +    suspend fun getFilms(): List<FilmItemMini>?
здесь nullable не обязательно, если в таблице ничего нет - придет пустой список

2022-12-14 20:18 UTC, palevominimale commented on domain/src/main/java/com/junopark/kpapi/domain/usecases/RoomUseCase.kt
>      suspend fun removeFilm(filmItemMini:FilmItemMini) = favsFilms.RemoveFilm(filmItemMini)
remove резонно делать по id

2022-12-15 11:28 UTC, LeskovBoris commented on domain/src/main/java/com/junopark/kpapi/domain/usecases/RoomUseCase.kt
> +    suspend fun getFilm(id:Int) = favsFilms.getFilm(id)
Сделал на всякий, если в БД будем сохранять подробную инфу о фильме по нажатию на элемент списка

2022-12-15 11:37 UTC, merged